dependencies:
- name: core-api-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: core-camera-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: core-monitor-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
- name: core-pos-emulator
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: core-pos-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: core-pos-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: core-recogniser-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.86
- name: core-rule-engine-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: core-sync-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: frontend-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.41
- name: inventory-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.33
- name: keras-retinanet-dev
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: middleware-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.13
- name: model-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.42
- name: pcluster-standalone
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.15
- name: pcrop-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.24
- name: pcrop-worker
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.15
- name: pdataset-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.13
- name: pdataset-worker
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.24
- name: pkube-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.43
- name: pmodel-management-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.24
- name: pmono-dataset
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: product-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.34
- name: proxy-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.76
- name: ptag-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.32
- name: ptag-frontend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.26
- name: ptag-log-proxy-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: ptag-proxy-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: ptag-watchdog
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.16
- name: ptransaction-watchdog
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.13
- name: transaction-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.22
